# -*- coding: utf-8 -*-
"""Mini_calculate.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fiTPJBMHoQoWXgSJapWxeMxcY1Pxu-2K
"""

# Day 1:
# Making a mini calculator in Python.
# Calculate your month expenses in mini calculator.

# Enter your Month_Income ....
Income = int(input("Enter your salary: "))
# Enter your all month expenses....
food = int(input('Enter food value: '))
clothes = int(input('Enter Clothes value: '))
electricity_cost = int(input('Enter electric_bill cost: '))
rent = int(input("Enter rent amount: "))
gas_bill = int(input("Enter gas_bill amount: "))
water_bill = int(input("Enter water_bill amount: "))
save_money = int(input("Enter your save amount "))

Total_pay = int(food + clothes + electricity_cost + rent + save_money +gas_bill + water_bill)
print("Total amount to pay: ", Total_pay)

# we know about how remaining money you've left .
money_left = Income - Total_pay
print("Remaining_amount:  ", money_left)